### ISSUE TITLE
how to get the Houston_gt.mat?

### ISSUE THREAD

**Issue by Spring-wind** [shuguang-52/AUSSC#1]
It's very clear how to get the 'Houston.mat', but I use the same file to process '2013_IEEE_GRSS_DF_Contest_LiDAR.tif', but it turns to be some continues number rather than the labels. Could you please tell me how to get the groudtruth label of Houston data? thank you so much!

**Comment by shuguang-52** [comment]
'geotif2mat.py' is only used for '2013_IEEE_GRSS_DF_Contest_Samples' to get the 'Houston.mat'. '2013_IEEE_GRSS_DF_Contest_LiDAR.tif' is used for Fusion of Hyperspectral and LiDAR Data, not HSI classification. To get the Houston_gt.mat, you need the software-ENVI (http://www.harrisgeospatial.com/docs/using_envi_Home.html). 

I have updated the README.md. The new README.md has the specific operation of extracting the required labels from ROI files using ENVI.

**Comment by Spring-wind** [comment]
thankyou so much！best wishes！


 
---Original---
