### ISSUE TITLE
get an error 'FailedPreconditionError: Attempting to use uninitialized value second_transition'

### ISSUE THREAD

**Issue by Ponytai1j** [shuguang-52/AUSSC#3]
run train, out puts an error :
> ---> 53         logits, prob = aucn_model.build_model(input_hsi, nb_classes, is_train=is_train, keep_prob=keep_prob)
>      54         pred = tf.argmax(prob, 1)
>      55         tf.add_to_collection('pred', pred)
> 
> 13 frames
> /content/drive/My Drive/my_research/model/AUSSC/Utils/aucn_model.py in build_model(input_images, num_output, is_train, keep_prob)
>      56                              strides=[1, 1, 1, 1, 1], padding='VALID')
>      57     print(pool1.get_shape())
> ---> 58     flatten = tf.layers.flatten(pool1)
>      59     #print(tf.__version__)
>      60     #flatten = tf.contrib.layers.flatten(pool1)
> 
> /tensorflow-1.15.2/python3.7/tensorflow_core/python/util/deprecation.py in new_func(*args, **kwargs)
>     322               'in a future version' if date is None else ('after %s' % date),
>     323               instructions)
> --> 324       return func(*args, **kwargs)

in fact when i use reshape instead of flatten the problem solved

```
flatten = tf.layers.flatten(pool1) # it doesnt work

other_dim = pool1.get_shape()[1]*pool1.get_shape()[2]*pool1.get_shape()[3]*pool1.get_shape()[4]
flatten = Reshape((other_dim,))(pool1) # it works
```
i just dont know why it corrpted there. Just create computational graph not excute why error says uninitalized? 
environment is tf 1.15.

**Comment by shuguang-52** [comment]
You may need to downgrade tensorflow to 1.11.0 or use tf.compat.v1. to replace tf.
